import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Text } from "@chakra-ui/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="green.300" h="100">
        <Link href="/login">Login</Link>
      </Box>
      <Box
        flex={1}
        display={"flex"}
        alignItems={"center"}
        justifyContent={"center"}
        h={"100vh"}
        bg={"red.400"}
        // p={100}
        textAlign={"center"}
      >
        <Text fontSize={"48"}>Home page</Text>
      </Box>
    </>
  );
}
